# Generated by Django 4.1.5 on 2023-01-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utsab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
