# Generated by Django 4.1.5 on 2023-01-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utsab', '0002_home_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='updated',
        ),
    ]
