# Generated by Django 4.1.5 on 2023-01-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utsab', '0003_remove_home_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='picture_1',
            field=models.ImageField(blank=True, null=True, upload_to='picture/'),
        ),
    ]
