# Generated by Django 4.1.5 on 2023-01-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utsab', '0004_skills_picture_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='picture_1',
        ),
    ]
